// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: viWxjihD78B5cQSNFM9rw3
// Component: qBMCobG68F
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_trubbi_is.module.css"; // plasmic-import: viWxjihD78B5cQSNFM9rw3/projectcss
import * as sty from "./PlasmicThjonusta.module.css"; // plasmic-import: qBMCobG68F/css

export type PlasmicThjonusta__VariantMembers = {};

export type PlasmicThjonusta__VariantsArgs = {};
type VariantPropType = keyof PlasmicThjonusta__VariantsArgs;
export const PlasmicThjonusta__VariantProps = new Array<VariantPropType>();

export type PlasmicThjonusta__ArgsType = {};
type ArgPropType = keyof PlasmicThjonusta__ArgsType;
export const PlasmicThjonusta__ArgProps = new Array<ArgPropType>();

export type PlasmicThjonusta__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultThjonustaProps {
  dataFetches: PlasmicThjonusta__Fetches;
}

function PlasmicThjonusta__RenderFunc(props: {
  variants: PlasmicThjonusta__VariantsArgs;
  args: PlasmicThjonusta__ArgsType;
  overrides: PlasmicThjonusta__OverridesType;
  dataFetches?: PlasmicThjonusta__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.all,
            projectcss.root_reset,
            sty.root
          )}
        />
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicThjonusta__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicThjonusta__VariantsArgs;
    args?: PlasmicThjonusta__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicThjonusta__Fetches;
  } & Omit<PlasmicThjonusta__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicThjonusta__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicThjonusta__ArgProps,
      internalVariantPropNames: PlasmicThjonusta__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicThjonusta__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicThjonusta";
  } else {
    func.displayName = `PlasmicThjonusta.${nodeName}`;
  }
  return func;
}

export const PlasmicThjonusta = Object.assign(
  // Top-level PlasmicThjonusta renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicThjonusta
    internalVariantProps: PlasmicThjonusta__VariantProps,
    internalArgProps: PlasmicThjonusta__ArgProps
  }
);

export default PlasmicThjonusta;
/* prettier-ignore-end */
