// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: viWxjihD78B5cQSNFM9rw3
// Component: w14lo9lxg7
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import PageLayout from "../../PageLayout"; // plasmic-import: --ZfzNn8OC/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_trubbi_is.module.css"; // plasmic-import: viWxjihD78B5cQSNFM9rw3/projectcss
import * as sty from "./PlasmicForsida.module.css"; // plasmic-import: w14lo9lxg7/css

export type PlasmicForsida__VariantMembers = {};

export type PlasmicForsida__VariantsArgs = {};
type VariantPropType = keyof PlasmicForsida__VariantsArgs;
export const PlasmicForsida__VariantProps = new Array<VariantPropType>();

export type PlasmicForsida__ArgsType = {};
type ArgPropType = keyof PlasmicForsida__ArgsType;
export const PlasmicForsida__ArgProps = new Array<ArgPropType>();

export type PlasmicForsida__OverridesType = {
  root?: p.Flex<"div">;
  pageLayout?: p.Flex<typeof PageLayout>;
  freeBox?: p.Flex<"div">;
};

export interface DefaultForsidaProps {
  dataFetches: PlasmicForsida__Fetches;
}

function PlasmicForsida__RenderFunc(props: {
  variants: PlasmicForsida__VariantsArgs;
  args: PlasmicForsida__ArgsType;
  overrides: PlasmicForsida__OverridesType;
  dataFetches?: PlasmicForsida__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{"Trúbbi.is"}</title>
        <meta key="og:title" property="og:title" content={"Trúbbi.is"} />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            defaultcss.all,
            projectcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <PageLayout
            data-plasmic-name={"pageLayout"}
            data-plasmic-override={overrides.pageLayout}
            className={classNames("__wab_instance", sty.pageLayout)}
            pageContent={
              <div
                data-plasmic-name={"freeBox"}
                data-plasmic-override={overrides.freeBox}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.freeBox
                )}
              />
            }
          />
        </p.Stack>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "pageLayout", "freeBox"],
  pageLayout: ["pageLayout", "freeBox"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  pageLayout: typeof PageLayout;
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicForsida__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicForsida__VariantsArgs;
    args?: PlasmicForsida__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicForsida__Fetches;
  } & Omit<PlasmicForsida__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicForsida__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicForsida__ArgProps,
      internalVariantPropNames: PlasmicForsida__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicForsida__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicForsida";
  } else {
    func.displayName = `PlasmicForsida.${nodeName}`;
  }
  return func;
}

export const PlasmicForsida = Object.assign(
  // Top-level PlasmicForsida renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    pageLayout: makeNodeComponent("pageLayout"),
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicForsida
    internalVariantProps: PlasmicForsida__VariantProps,
    internalArgProps: PlasmicForsida__ArgProps
  }
);

export default PlasmicForsida;
/* prettier-ignore-end */
