// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 6t8zkvgddX7FsFBrxzeJqm
// Component: 6jpY3MwLkh
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_trubbi_library.module.css"; // plasmic-import: 6t8zkvgddX7FsFBrxzeJqm/projectcss
import * as sty from "./PlasmicNumberBubble.module.css"; // plasmic-import: 6jpY3MwLkh/css

export type PlasmicNumberBubble__VariantMembers = {};

export type PlasmicNumberBubble__VariantsArgs = {};
type VariantPropType = keyof PlasmicNumberBubble__VariantsArgs;
export const PlasmicNumberBubble__VariantProps = new Array<VariantPropType>();

export type PlasmicNumberBubble__ArgsType = {
  children?: React.ReactNode;
};

type ArgPropType = keyof PlasmicNumberBubble__ArgsType;
export const PlasmicNumberBubble__ArgProps = new Array<ArgPropType>("children");

export type PlasmicNumberBubble__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultNumberBubbleProps {
  children?: React.ReactNode;
  className?: string;
}

function PlasmicNumberBubble__RenderFunc(props: {
  variants: PlasmicNumberBubble__VariantsArgs;
  args: PlasmicNumberBubble__ArgsType;
  overrides: PlasmicNumberBubble__OverridesType;
  dataFetches?: PlasmicNumberBubble__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        defaultcss.all,
        projectcss.all,
        projectcss.root_reset,
        sty.root
      )}
    >
      {p.renderPlasmicSlot({
        defaultContents: "1",
        value: args.children,
        className: classNames(sty.slotTargetChildren)
      })}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNumberBubble__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNumberBubble__VariantsArgs;
    args?: PlasmicNumberBubble__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicNumberBubble__Fetches;
  } & Omit<PlasmicNumberBubble__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicNumberBubble__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicNumberBubble__ArgProps,
      internalVariantPropNames: PlasmicNumberBubble__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicNumberBubble__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNumberBubble";
  } else {
    func.displayName = `PlasmicNumberBubble.${nodeName}`;
  }
  return func;
}

export const PlasmicNumberBubble = Object.assign(
  // Top-level PlasmicNumberBubble renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicNumberBubble
    internalVariantProps: PlasmicNumberBubble__VariantProps,
    internalArgProps: PlasmicNumberBubble__ArgProps
  }
);

export default PlasmicNumberBubble;
/* prettier-ignore-end */
